version: '3.8'

services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build: .
    volumes:
      - '.:/var/www/html'

    ports:
      - 80:80

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  dbdata:
